# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('play_num', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harmony', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-harmony'],
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propose.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('score', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22)),
                ('is_title', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propose.Track'),
        ),
        migrations.AddField(
            model_name='mtm',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propose.Tag'),
        ),
        migrations.AddField(
            model_name='mtm',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propose.Track'),
        ),
    ]
