# -*- coding:utf-8 -*-

# A simple example using the HTTP plugin that shows the retrieval of a
# single page via HTTP. 
#
# This script is automatically generated by ngrinder.
#
# @author admin
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest
from net.grinder.plugin.http import HTTPPluginControl
from java.util import Date
from HTTPClient import NVPair, Cookie, CookieModule

control = HTTPPluginControl.getConnectionDefaults()
# if you don't want that HTTPRequest follows the redirection, please modify the following option 0.
control.followRedirects = 0
# if you want to increase the timeout, please modify the following option.
#control.timeout = 7000

test1 = Test(1, "wlxyzlw.iptime.org")
request1 = HTTPRequest()

# Set header datas
headers = [] # Array of NVPair
# Set param datas
params = [] # Array of NVPair
# Set cookie datas
cookies = [] # Array of Cookie

class TestRunner:
	# initlialize a thread 
	def __init__(self):
		test1.record(TestRunner.__call__)
		
		grinder.statistics.delayReports=True
		pass
	
	def before(self):
		request1.headers = headers
		for c in cookies: CookieModule.addCookie(c, HTTPPluginControl.getThreadHTTPClientContext())
	def page1(self):
		result = request1.GET(
"http://wlxyzlw.iptime.org:8088/address/"+unicode("경기도성남시","utf-8")+"/proposal/", params)
		grinder.sleep(6000)
		return result
	# test method		
	def __call__(self):
		result=0
		self.before()
		result = self.page1()
		grinder.sleep(6000)
		#if result.getStatusCode() in (301, 302) :
			# grinder.logger.warn("Warning. The response may not be correct. The response code was %d." %  result.getStatusCode()) 
			
		def __del__(self) :
			grinder.logger.info("Deletion");
